apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fuehrungszeugnis.fullname" . }}
  labels:
    {{- include "fuehrungszeugnis.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE__PASSWORD: {{ include "fuehrungszeugnis.dbPassword" . | b64enc | quote }}
  PAPERLESS__TOKEN: {{ .Values.secrets.paperlessToken | b64enc | quote }}
  HITOBITO__TOKEN: {{ .Values.secrets.hitobitoToken | b64enc | quote }}
  EMAIL__SMTP_PASSWORD: {{ .Values.secrets.emailSmtpPassword | b64enc | quote }}
